export const category = {
  GET_CATEGORIES: "GET_CATEGORIES",
  GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
  GET_CATEGORIES_LOADING: "GET_CATEGORIES_LOADING",
  GET_CATEGORIES_FAILURE: "GET_CATEGORIES_FAILURE",
  GET_CATEGORIES_RESET: "GET_CATEGORIES_RESET",

  CREATE_CATEGORY: "CREATE_CATEGORY",
  CREATE_CATEGORY_SUCCESS: "CREATE_CATEGORY_SUCCESS",
  CREATE_CATEGORY_LOADING: "CREATE_CATEGORY_LOADING",
  CREATE_CATEGORY_FAILURE: "CREATE_CATEGORY_FAILURE",
  CREATE_CATEGORY_RESET: "CREATE_CATEGORY_RESET",

  UPDATE_CATEGORY: "UPDATE_CATEGORY",
  UPDATE_CATEGORY_SUCCESS: "UPDATE_CATEGORY_SUCCESS",
  UPDATE_CATEGORY_LOADING: "UPDATE_CATEGORY_LOADING",
  UPDATE_CATEGORY_FAILURE: "UPDATE_CATEGORY_FAILURE",
  UPDATE_CATEGORY_RESET: "UPDATE_CATEGORY_RESET",

  DELETE_CATEGORY: "DELETE_CATEGORY",
  DELETE_CATEGORY_SUCCESS: "DELETE_CATEGORY_SUCCESS",
  DELETE_CATEGORY_LOADING: "DELETE_CATEGORY_LOADING",
  DELETE_CATEGORY_FAILURE: "DELETE_CATEGORY_FAILURE",
  DELETE_CATEGORY_RESET: "DELETE_CATEGORY_RESET",
};