export const auth = {
  LOGIN: "LOGIN",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_LOADING: "LOGIN_LOADING",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_RESET: "LOGIN_RESET",

  LOGOUT: "LOGOUT",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_LOADING: "LOGOUT_LOADING",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  LOGOUT_RESET: "LOGOUT_RESET",

  SIGNUP: "SIGNUP",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
  SIGNUP_LOADING: "SIGNUP_LOADING",
  SIGNUP_FAILURE: "SIGNUP_FAILURE",
  SIGNUP_RESET: "SIGNUP_RESET",
};