export const taskPriority = {
  GET_PRIORITIES: "GET_PRIORITIES",
  GET_PRIORITIES_SUCCESS: "GET_PRIORITIES_SUCCESS",
  GET_PRIORITIES_LOADING: "GET_PRIORITIES_LOADING",
  GET_PRIORITIES_FAILURE: "GET_PRIORITIES_FAILURE",
  GET_PRIORITIES_RESET: "GET_PRIORITIES_RESET",

  CREATE_PRIORITY: "CREATE_PRIORITY",
  CREATE_PRIORITY_SUCCESS: "CREATE_PRIORITY_SUCCESS",
  CREATE_PRIORITY_LOADING: "CREATE_PRIORITY_LOADING",
  CREATE_PRIORITY_FAILURE: "CREATE_PRIORITY_FAILURE",
  CREATE_PRIORITY_RESET: "CREATE_PRIORITY_RESET",

  UPDATE_PRIORITY: "UPDATE_PRIORITY",
  UPDATE_PRIORITY_SUCCESS: "UPDATE_PRIORITY_SUCCESS",
  UPDATE_PRIORITY_LOADING: "UPDATE_PRIORITY_LOADING",
  UPDATE_PRIORITY_FAILURE: "UPDATE_PRIORITY_FAILURE",
  UPDATE_PRIORITY_RESET: "UPDATE_PRIORITY_RESET",

  DELETE_PRIORITY: "DELETE_PRIORITY",
  DELETE_PRIORITY_SUCCESS: "DELETE_PRIORITY_SUCCESS",
  DELETE_PRIORITY_LOADING: "DELETE_PRIORITY_LOADING",
  DELETE_PRIORITY_FAILURE: "DELETE_PRIORITY_FAILURE",
  DELETE_PRIORITY_RESET: "DELETE_PRIORITY_RESET",
};