export const taskStatus = {
  GET_STATUS: "GET_STATUS",
  GET_STATUS_SUCCESS: "GET_STATUS_SUCCESS",
  GET_STATUS_LOADING: "GET_STATUS_LOADING",
  GET_STATUS_FAILURE: "GET_STATUS_FAILURE",
  GET_STATUS_RESET: "GET_STATUS_RESET",

  CREATE_STATUS: "CREATE_STATUS",
  CREATE_STATUS_SUCCESS: "CREATE_STATUS_SUCCESS",
  CREATE_STATUS_LOADING: "CREATE_STATUS_LOADING",
  CREATE_STATUS_FAILURE: "CREATE_STATUS_FAILURE",
  CREATE_STATUS_RESET: "CREATE_STATUS_RESET",

  UPDATE_STATUS: "UPDATE_STATUS",
  UPDATE_STATUS_SUCCESS: "UPDATE_STATUS_SUCCESS",
  UPDATE_STATUS_LOADING: "UPDATE_STATUS_LOADING",
  UPDATE_STATUS_FAILURE: "UPDATE_STATUS_FAILURE",
  UPDATE_STATUS_RESET: "UPDATE_STATUS_RESET",

  DELETE_STATUS: "DELETE_STATUS",
  DELETE_STATUS_SUCCESS: "DELETE_STATUS_SUCCESS",
  DELETE_STATUS_LOADING: "DELETE_STATUS_LOADING",
  DELETE_STATUS_FAILURE: "DELETE_STATUS_FAILURE",
  DELETE_STATUS_RESET: "DELETE_STATUS_RESET",
};