export const dashboard = {
  GET_DASHBOARD: "GET_DASHBOARD",
  GET_DASHBOARD_LOADING: "GET_DASHBOARD_LOADING",
  GET_DASHBOARD_SUCCESS: "GET_DASHBOARD_SUCCESS",
  GET_DASHBOARD_FAILURE: "GET_DASHBOARD_FAILURE",
  GET_DASHBOARD_RESET: "GET_DASHBOARD_RESET",
};