export const task = {
  GET_TASKS: "GET_TASKS",
  GET_TASKS_SUCCESS: "GET_TASKS_SUCCESS",
  GET_TASKS_LOADING: "GET_TASKS_LOADING",
  GET_TASKS_FAILURE: "GET_TASKS_FAILURE",
  GET_TASKS_RESET: "GET_TASKS_RESET",

  CREATE_TASK: "CREATE_TASK",
  CREATE_TASK_SUCCESS: "CREATE_TASK_SUCCESS",
  CREATE_TASK_LOADING: "CREATE_TASK_LOADING",
  CREATE_TASK_FAILURE: "CREATE_TASK_FAILURE",
  CREATE_TASK_RESET: "CREATE_TASK_RESET",

  UPDATE_TASK: "UPDATE_TASK",
  UPDATE_TASK_SUCCESS: "UPDATE_TASK_SUCCESS",
  UPDATE_TASK_LOADING: "UPDATE_TASK_LOADING",
  UPDATE_TASK_FAILURE: "UPDATE_TASK_FAILURE",
  UPDATE_TASK_RESET: "UPDATE_TASK_RESET",

  DELETE_TASK: "DELETE_TASK",
  DELETE_TASK_SUCCESS: "DELETE_TASK_SUCCESS",
  DELETE_TASK_LOADING: "DELETE_TASK_LOADING",
  DELETE_TASK_FAILURE: "DELETE_TASK_FAILURE",
  DELETE_TASK_RESET: "DELETE_TASK_RESET",
};